const SECTIONS = [
  {id:'basics', label:'Basics'}, {id:'hero', label:'Hero'}, {id:'about', label:'About'},
  {id:'services', label:'Services'}, {id:'results', label:'Results'}, {id:'pricing', label:'Pricing'},
  {id:'testimonial', label:'Testimonial'}, {id:'faq', label:'FAQ'}, {id:'contact', label:'Contact'}, {id:'style', label:'Colours'}
];
let data = {}; let current = 'basics'; let password = localStorage.getItem('fiaz_admin_password') || '';
const $ = (id)=>document.getElementById(id);
const field = (key,label,type='text',help='') => `<div class="field"><label>${label}</label>${type==='textarea'?`<textarea data-key="${key}">${esc(data[key]||'')}</textarea>`:type==='color'?`<input data-key="${key}" type="color" value="${esc(data[key]||'#000000')}">`:`<input data-key="${key}" value="${esc(data[key]||'')}">`}${help?`<div class="help">${help}</div>`:''}</div>`;
const imageField = (key,label)=>`<div class="field"><label>${label}</label><input data-key="${key}" value="${esc(data[key]||'')}"><input type="file" accept="image/*" data-upload="${key}"><img class="preview" src="${esc(data[key]||'')}" onerror="this.style.display='none'" /></div>`;
function esc(v){return String(v).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function getPassword(){return password || $('password').value.trim()}
async function api(path, opts={}){const res=await fetch(path,{...opts,headers:{'Content-Type':'application/json','X-Admin-Password':getPassword(),...(opts.headers||{})}}); if(!res.ok) throw new Error(await res.text()); return res.json();}
async function login(){try{password=$('password').value.trim(); const r=await api('/api/content'); data=r.data; localStorage.setItem('fiaz_admin_password',password); $('login').classList.add('hidden'); $('editor').classList.remove('hidden'); renderTabs(); render(); setStatus('Logged in. Let’s cook.',true)}catch(e){$('loginMsg').textContent='Login failed. Check the password.'}}
async function load(){if(!password) return; try{const r=await api('/api/content'); data=r.data; $('login').classList.add('hidden'); $('editor').classList.remove('hidden'); renderTabs(); render();}catch(e){localStorage.removeItem('fiaz_admin_password');}}
function renderTabs(){ $('tabs').innerHTML=SECTIONS.map(s=>`<button type="button" class="tab ${s.id===current?'active':''}" data-tab="${s.id}">${s.label}</button>`).join(''); document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{collect(); current=b.dataset.tab; renderTabs(); render();});}
function panel(title,inner,full=false){return `<section class="panel ${full?'full':''}"><h2>${title}</h2>${inner}</section>`}
function render(){let html='';
 if(current==='basics') html=panel('SEO & Branding', field('seoTitle','Browser title')+field('seoDescription','Google description','textarea')+field('brandName','Business name')+imageField('logo','Logo'))+panel('Navigation', listEditor('navLinks',['label','url']));
 if(current==='hero') html=panel('Hero section', imageField('heroImage','Hero photo')+field('heroBadge','Small badge text')+field('heroLine1','Heading line 1')+field('heroLine2','Heading line 2 - gold text')+field('heroLine3','Heading line 3')+field('heroText','Hero paragraph','textarea')+field('primaryButtonText','Main button text')+field('primaryButtonLink','Main button link')+field('secondaryButtonText','Second button text')+field('secondaryButtonLink','Second button link'),true)+panel('Stats', listEditor('stats',['number','label']),true);
 if(current==='about') html=panel('About section', imageField('aboutImage','About photo')+field('aboutKicker','Small heading')+field('aboutTitle','Main heading')+field('aboutText','Paragraph','textarea'),true)+panel('Bullet points', simpleList('aboutPoints'),true);
 if(current==='services') html=panel('Services intro', field('servicesKicker','Small heading')+field('servicesTitle','Main heading')+field('servicesText','Paragraph','textarea')+field('bannerText','Banner text'),true)+panel('Services', listEditor('services',['small','title','text']),true);
 if(current==='results') html=panel('Results intro', field('resultsKicker','Small heading')+field('resultsTitle','Main heading')+field('resultsText','Paragraph','textarea'),true)+panel('Result cards', resultEditor(),true);
 if(current==='pricing') html=panel('Pricing intro', field('pricingKicker','Small heading')+field('pricingTitle','Main heading')+field('pricingText','Paragraph','textarea'),true)+panel('Packages', packageEditor(),true);
 if(current==='testimonial') html=panel('Testimonial', field('testimonialKicker','Small heading')+field('testimonialTitle','Main heading')+field('testimonialText','Testimonial text','textarea')+field('testimonialName','Client name'),true);
 if(current==='faq') html=panel('FAQ heading', field('faqKicker','Small heading')+field('faqTitle','Main heading'),true)+panel('Questions', listEditor('faqs',['question','answer']),true);
 if(current==='contact') html=panel('Final CTA & Links', field('finalKicker','Small heading')+field('finalTitle','Main heading')+field('finalText','Paragraph','textarea')+field('email','Email address')+field('emailButtonText','Email button text')+field('instagram','Instagram link')+field('tiktok','TikTok link')+field('youtube','YouTube link')+field('footerText','Footer text'),true);
 if(current==='style') html=panel('Brand colours', ['backgroundColor','cardColor','mainTextColor','bodyTextColor','goldColor','buttonTextColor'].map(k=>field(k,k.replace(/Color/,' colour'),'color')).join(''),true);
 $('form').innerHTML=html; wireUploads();}
function simpleList(key){data[key]=data[key]||[];return `<div data-list="${key}">${data[key].map((v,i)=>`<div class="list-item"><textarea data-arr="${key}" data-i="${i}">${esc(v)}</textarea><div class="mini-actions"><button type="button" class="danger" onclick="removeItem('${key}',${i})">Remove</button></div></div>`).join('')}</div><button type="button" class="add" onclick="addItem('${key}','')">Add item</button>`}
function listEditor(key,fields){data[key]=data[key]||[];return data[key].map((obj,i)=>`<div class="list-item">${fields.map(f=>`<div class="field"><label>${f}</label><textarea data-obj="${key}" data-i="${i}" data-f="${f}">${esc(obj[f]||'')}</textarea></div>`).join('')}<div class="mini-actions"><button type="button" class="danger" onclick="removeItem('${key}',${i})">Remove</button></div></div>`).join('')+`<button type="button" class="add" onclick="addItem('${key}',{})">Add item</button>`}
function resultEditor(){data.results=data.results||[];return data.results.map((obj,i)=>`<div class="list-item"><div class="row"><div class="field"><label>Label</label><input data-obj="results" data-i="${i}" data-f="label" value="${esc(obj.label||'')}"></div><div class="field"><label>Image</label><input data-obj="results" data-i="${i}" data-f="image" value="${esc(obj.image||'')}"><input type="file" accept="image/*" data-upload-list="results" data-i="${i}" data-f="image"><img class="preview" src="${esc(obj.image||'')}" onerror="this.style.display='none'"></div></div><button type="button" class="danger" onclick="removeItem('results',${i})">Remove</button></div>`).join('')+`<button type="button" class="add" onclick="addItem('results',{image:'/images/uploads/client1.svg',label:'New result'})">Add result</button>`}
function packageEditor(){data.packages=data.packages||[];return data.packages.map((p,i)=>`<div class="list-item"><div class="row three"><div class="field"><label>Name</label><input data-obj="packages" data-i="${i}" data-f="name" value="${esc(p.name||'')}"></div><div class="field"><label>Price</label><input data-obj="packages" data-i="${i}" data-f="price" value="${esc(p.price||'')}"></div><div class="field"><label>Button</label><input data-obj="packages" data-i="${i}" data-f="button" value="${esc(p.button||'')}"></div></div><div class="field"><label>Bullet points, one per line</label><textarea data-package-items="${i}">${esc((p.items||[]).join('\n'))}</textarea></div><label><input type="checkbox" data-package-featured="${i}" ${p.featured?'checked':''}> Featured package</label><div class="mini-actions"><button type="button" class="danger" onclick="removeItem('packages',${i})">Remove</button></div></div>`).join('')+`<button type="button" class="add" onclick="addItem('packages',{name:'New package',price:'£',button:'Enquire',items:['Point one'],featured:false})">Add package</button>`}
function collect(){document.querySelectorAll('[data-key]').forEach(el=>data[el.dataset.key]=el.value);document.querySelectorAll('[data-arr]').forEach(el=>data[el.dataset.arr][+el.dataset.i]=el.value);document.querySelectorAll('[data-obj]').forEach(el=>data[el.dataset.obj][+el.dataset.i][el.dataset.f]=el.value);document.querySelectorAll('[data-package-items]').forEach(el=>data.packages[+el.dataset.packageItems].items=el.value.split('\n').filter(Boolean));document.querySelectorAll('[data-package-featured]').forEach(el=>data.packages[+el.dataset.packageFeatured].featured=el.checked);}
window.addItem=(key,val)=>{collect();data[key].push(typeof val==='object'?JSON.parse(JSON.stringify(val)):val);render()}; window.removeItem=(key,i)=>{collect();data[key].splice(i,1);render()};
function setStatus(msg,ok){$('status').textContent=msg;$('status').className=ok?'status-ok':'status-bad'}
async function save(){collect(); setStatus('Saving...',true); try{await api('/api/content',{method:'POST',body:JSON.stringify(data)}); setStatus('Saved. Cloudflare will update in about a minute.',true)}catch(e){setStatus('Save failed: '+e.message,false)}}
function wireUploads(){document.querySelectorAll('[data-upload]').forEach(inp=>inp.onchange=async()=>upload(inp.files[0],p=>{data[inp.dataset.upload]=p;render()}));document.querySelectorAll('[data-upload-list]').forEach(inp=>inp.onchange=async()=>upload(inp.files[0],p=>{data[inp.dataset.uploadList][+inp.dataset.i][inp.dataset.f]=p;render()}));}
async function upload(file,done){if(!file)return; setStatus('Uploading image...',true); const b64=await toBase64(file); const r=await api('/api/upload',{method:'POST',body:JSON.stringify({name:file.name,type:file.type,data:b64})}); done(r.path); setStatus('Image uploaded. Remember to save website.',true)}
function toBase64(file){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result.split(',')[1]);fr.onerror=reject;fr.readAsDataURL(file);});}
$('loginBtn').onclick=login; $('saveBtn').onclick=save; load();
